version: '3.5'
services:
    sig_svr:
        image: novice/ss:latest
        deploy:
            mode: global
        environment:
            # If you want to change the signaling service listening port
            - PORT=57000
            # change bt-tracker's port
            - TRACKER_PORT=2018
            # and turnserver account
            - TURN_USER=piaoyun
            - TURN_PASS=freego
        networks:
            - outside
networks:
  outside:
    external: true
    name: "host"




