version: '3.5'
services:
    sig_svr:
        image: novice/ss:latest
        deploy:
            mode: global
        networks:
            - outside
networks:
  outside:
    external: true
    name: "host"




