version: '3.5'
services:
    sig_svr:
        image: novice/ss:latest
        deploy:
            mode: global
        environment:
            # If you want to change the signaling service listening port
            - PORT=57000
        networks:
            - outside
networks:
  outside:
    external: true
    name: "host"




